<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_E-mail ke qatestinggmail.com</name>
   <tag></tag>
   <elementGuidId>2171ca20-0234-4f7b-8ab8-34a86559ebda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__skipper']/div/div/div/div[2]/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-kdt10q</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a37e8393-4e79-44da-a0e7-70851b8108b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a52bef47-8fab-442a-ad91-9f9e6e5f3c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kdt10q</value>
      <webElementGuid>78c6520f-a940-4140-b34f-3392c214a772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-mail ke qatesting@gmail.com</value>
      <webElementGuid>28caad1f-242b-44ad-96fe-4b50af1bf3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__skipper&quot;)/div[@class=&quot;css-b1khel&quot;]/div[@class=&quot;css-kqvkc7&quot;]/div[@class=&quot;css-1akx9dq&quot;]/div[@class=&quot;css-rrvbed&quot;]/div[@class=&quot;css-j5mr2z&quot;]/div[@class=&quot;css-1ogrxxd&quot;]/div[@class=&quot;css-kdt10q&quot;]</value>
      <webElementGuid>af2e4c10-6823-4a14-9b6f-2b566bf8a6ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__skipper']/div/div/div/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>12fdc6a7-0892-4c52-bff2-8cb275abae0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Metode Verifikasi'])[1]/following::div[3]</value>
      <webElementGuid>1139f2c1-f733-4eb9-890d-1461fbe6f49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div</value>
      <webElementGuid>91210480-3e36-4f10-94d6-8adfac24ceef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'E-mail ke qatesting@gmail.com' or . = 'E-mail ke qatesting@gmail.com')]</value>
      <webElementGuid>31d4077e-8634-4afa-a216-850e2fda8fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
