<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Daftar</name>
   <tag></tag>
   <elementGuidId>b63ababf-fbd0-4379-bec8-6ee55c3bc90c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__skipper']/div/div/div/div[2]/div[4]/form/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.css-kt8ee4 > span.css-bp4m37</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;btn-submit&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cc7d10e7-f55e-490a-85a1-ad13669b106a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-bp4m37</value>
      <webElementGuid>d30b346a-d5c8-4379-9bb9-1cee67098dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>9734e970-93b5-4cf0-a8c9-d8ba70851065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__skipper&quot;)/div[@class=&quot;css-b1khel&quot;]/div[@class=&quot;css-kqvkc7&quot;]/div[@class=&quot;css-1akx9dq&quot;]/div[@class=&quot;css-rrvbed&quot;]/div[4]/form[1]/button[@class=&quot;css-kt8ee4&quot;]/span[@class=&quot;css-bp4m37&quot;]</value>
      <webElementGuid>00f8a80d-9f99-457f-ad06-c5941fe89211</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__skipper']/div/div/div/div[2]/div[4]/form/button/span</value>
      <webElementGuid>c6ceca1e-68d7-4526-8eef-7718a8327eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor HP atau E-mail'])[2]/following::span[1]</value>
      <webElementGuid>33630356-d8bf-4286-992d-319e351328db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor HP atau E-mail'])[1]/following::span[1]</value>
      <webElementGuid>8fcfe219-e51c-46fb-bec4-9a3c35594edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dengan mendaftar, saya menyetujui'])[1]/preceding::span[1]</value>
      <webElementGuid>c3aba9e1-824b-49d7-9d8e-54f7d11b8a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat &amp; Ketentuan'])[1]/preceding::span[1]</value>
      <webElementGuid>a112d1cb-439b-4b86-827f-5ebd0087bcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>0b82218d-4bc8-4c46-8444-5be803ab39cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>23f3fe45-9dad-42b2-92ee-3d08a6ac2fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>43d96abb-7bfe-42f2-b929-b5bacf64fc91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
