<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rp249.000__0m9NsWypn6Yr4lxFi5dknA NWVIh_eaa365</name>
   <tag></tag>
   <elementGuidId>ec454af8-027b-43ac-a75a-d2c4222da14b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[4]/div/div/a/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;product-image Ad jam tangan kulit analog pria original 99l546 - Hitam Rp200.000 shop badge 99Light Jakarta Barat three dots&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a64795df-8e9f-4288-b61a-7bc87026abd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>product-image</value>
      <webElementGuid>c3ccbca2-6338-4c43-8c2d-482a7392de61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.tokopedia.net/img/cache/200-square/VqbcmM/2025/4/9/6b5455ec-a8e9-4c80-8bf4-be48bf60b00e.jpg.webp?ect=4g</value>
      <webElementGuid>e92c9474-fc6a-4da1-b5dc-6b850ef8acda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_0m9NsWypn6Yr4lxFi5dknA== NWVIhquIvF0Jc0Qlizjluw==</value>
      <webElementGuid>016cce39-c6fc-4954-b72a-7bc2a90954be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>7becb85e-14a6-4fa5-95d9-c7f6d2b93ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>08d22aab-61de-4e02-b085-8e65688598ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[4]/div[@class=&quot;css-jza1fo&quot;]/div[@class=&quot;css-5wh65g&quot;]/a[@class=&quot;oQ94Awb6LlTiGByQZo8Lyw== IM26HEnTb-krJayD-R0OHw==&quot;]/div[@class=&quot;bYD8FcVCFyOBiVyITwDj1Q==&quot;]/div[@class=&quot;FsRHU-HdyqHfg3GrIQNUWA==&quot;]/div[@class=&quot;Het-JIVjmDQQceOwOkdz3A==&quot;]/div[@class=&quot;RftQkSj-U+4lIFBAIpsz3Q== responsive EXUyQTyJzTrmf3n3cdbJjA==&quot;]/img[@class=&quot;_0m9NsWypn6Yr4lxFi5dknA== NWVIhquIvF0Jc0Qlizjluw==&quot;]</value>
      <webElementGuid>190e904d-8706-4cd6-8c8e-ccba363f1194</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[4]/div/div/a/div/div/div/div/img</value>
      <webElementGuid>a41a0f09-5d38-4649-86d2-5a8362448d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='product-image'])[4]</value>
      <webElementGuid>9acabe4f-59a7-40b8-b55b-143d9db7de25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a/div/div/div/div/img</value>
      <webElementGuid>1e1f2d32-3609-4c7e-b3dd-615b24be8c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'product-image' and @src = 'https://images.tokopedia.net/img/cache/200-square/VqbcmM/2025/4/9/6b5455ec-a8e9-4c80-8bf4-be48bf60b00e.jpg.webp?ect=4g']</value>
      <webElementGuid>504b9fdc-ddea-49bb-8340-677711299300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
