<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Detail</name>
   <tag></tag>
   <elementGuidId>1c7117bc-040a-4251-aa38-2a16e6f11bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_detail']/div[2]/div/div/button/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1a9ka7b-unf-tab-holder.ehv0kkf2 > button.tab-item.css-3lvael.ehv0kkf3 > p.css-s30ezu-unf-heading.e1qvo2ff8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;tabPDPDetail&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>674ca825-93af-4f0c-b2df-ba312aad9a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>fe67cfd6-c3a3-459f-9e14-59532a4054dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-s30ezu-unf-heading e1qvo2ff8</value>
      <webElementGuid>50829246-977c-43ca-b731-caa278f81ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>27ae94c8-658f-46e9-a418-66f897078aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_detail&quot;)/div[2]/div[@class=&quot;css-1bl48du-unf-tab-wrapper ehv0kkf0&quot;]/div[@class=&quot;css-1a9ka7b-unf-tab-holder ehv0kkf2&quot;]/button[@class=&quot;tab-item css-3lvael ehv0kkf3&quot;]/p[@class=&quot;css-s30ezu-unf-heading e1qvo2ff8&quot;]</value>
      <webElementGuid>2ad421ec-4f64-490d-9a0a-170d3ed90654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_detail']/div[2]/div/div/button/p</value>
      <webElementGuid>df0ed845-7220-4447-957e-ebf45893587d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp284.000'])[2]/following::p[1]</value>
      <webElementGuid>15ae4fa9-38b8-4c30-997f-25695b5292c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi:'])[1]/preceding::p[2]</value>
      <webElementGuid>f804f023-c725-4633-a723-cb109d06bb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/preceding::p[2]</value>
      <webElementGuid>15f86005-09f0-4110-9930-edca6d98ae59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>3db7b98a-4a1e-4a51-9982-dcc8f7029d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/p</value>
      <webElementGuid>3eae4d79-9a30-4a06-b3cc-4498b5d2f9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>8012ba9d-967b-4480-a82f-d82dc060ebfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
